# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepagecounter_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBadgePanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('url', models.CharField(max_length=40)),
                ('badge_icon_class', models.CharField(max_length=20)),
                ('badge_header_text', models.CharField(max_length=50)),
                ('badge_description', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='pages.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
