# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_faqpage_faqpageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='header_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
