# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_timelinepage_timelinepageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinepageitem',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
