# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 10:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_graphpage_graphpagesliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphpagesliderimage',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='pages.GraphPage'),
        ),
    ]
