# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 10:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180313_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
