# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('pages', '0013_regularpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
