# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180118_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecentity',
            name='title_given',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
