# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180119_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fecentity',
            options={'ordering': ('date', 'title'), 'verbose_name': 'FEC Entity', 'verbose_name_plural': 'FEC Entities'},
        ),
    ]
