# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20180226_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecentity',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='title_given',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
