# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180305_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecentity',
            name='title_given',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
