# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180305_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecentity',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
