# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20180305_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecentity',
            name='associated_corporations',
            field=models.ManyToManyField(blank=True, null=True, related_name='associated_corporations', to='records.Corporation'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='associated_people',
            field=models.ManyToManyField(blank=True, null=True, related_name='associated_people', to='records.Person'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, to='records.Country'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='subject_corporations',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject_corporations', to='records.Corporation'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='subject_people',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject_people', to='records.Person'),
        ),
    ]
