# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20180326_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fec_associated_person',
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fec_person_roles',
            },
        ),
        migrations.RemoveField(
            model_name='fecentity',
            name='associated_people',
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='associated_corporations',
            field=models.ManyToManyField(blank=True, related_name='associated_corporations', to='records.Corporation'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='countries',
            field=models.ManyToManyField(blank=True, to='records.Country'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='subject_corporations',
            field=models.ManyToManyField(blank=True, related_name='subject_corporations', to='records.Corporation'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='subject_people',
            field=models.ManyToManyField(blank=True, related_name='subject_people', to='records.Person'),
        ),
        migrations.AddField(
            model_name='associatedperson',
            name='fec_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_people', to='records.FECEntity'),
        ),
        migrations.AddField(
            model_name='associatedperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Person'),
        ),
    ]
