# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20180327_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedperson',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.PersonRole'),
        ),
    ]
