# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_associatedperson_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedperson',
            name='person',
            field=models.ForeignKey(help_text=b'Person appears in the header.', on_delete=django.db.models.deletion.CASCADE, to='records.Person'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='associated_corporations',
            field=models.ManyToManyField(blank=True, help_text=b'Corporations appearing in the header.', related_name='associated_corporations', to='records.Corporation'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='confidential',
            field=models.BooleanField(default=False, verbose_name=b'Message is confidential.'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text=b'Countries mentioned in the telex message.', to='records.Country'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='date',
            field=models.DateField(blank=True, help_text=b'Date of the telex message. Example: 1960-04-15', null=True),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='doc_name',
            field=models.CharField(help_text=b'The number of the telex message. Example: 35_0015', max_length=100),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='is_coded',
            field=models.BooleanField(default=False, verbose_name=b'Message is a coded message.'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='is_handwritten',
            field=models.BooleanField(default=False, verbose_name=b'Message is handwritten.'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='pages',
            field=models.IntegerField(help_text=b'Number of the pages'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='place',
            field=models.ForeignKey(default=1, help_text=b'Origin of the telex message. Example: MUN-4', on_delete=django.db.models.deletion.CASCADE, to='records.Place'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='subject_corporations',
            field=models.ManyToManyField(blank=True, help_text=b'Corporations mentioned in the telex message.', related_name='subject_corporations', to='records.Corporation'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='subject_people',
            field=models.ManyToManyField(blank=True, help_text=b'People mentioned in the telex message.', related_name='subject_people', to='records.Person'),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='title',
            field=models.CharField(blank=True, help_text=b'Title of the telex message. Example: MUN-4', max_length=150),
        ),
        migrations.AlterField(
            model_name='fecentity',
            name='title_given',
            field=models.CharField(blank=True, help_text=b'Given title. Example: New York Guild Contract', max_length=150, null=True),
        ),
    ]
